@ECHO OFF

:: THIS SCRIPT REGENERATES THE TRANSLATIONS FILE (FDISK.LNG) AS WELL AS THE
:: DEFLANG.C FILE THAT IS NEEDED AT FDISK'S COMPILE TIME.

..\SVARLANG\TLUMACZ en pl

IF EXIST ..\DEFLANG.C DEL ..\DEFLANG.C
IF EXIST ..\FDISK.LNG DEL ..\FDISK.LNG

MOVE DEFLANG.C ..
MOVE OUT.LNG ..\FDISK.LNG
