name: Build master with Open Watcom v2 (Linux)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Build with wmake
      run: |
        cd source/fdisk
        wmake

    - name: Build distribution ZIP
      run: |
        cd source/fdisk
        wmake dist

    - name: Upload files
      uses: actions/upload-artifact@v3
      with:
        name: fdisk.zip
        path: fdisk.zip

